// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.1
// source: api/proto/interaction/v1/interaction.proto

package interactionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InteractionServiceClient is the client API for InteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionServiceClient interface {
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	CreateRating(ctx context.Context, in *CreateRatingRequest, opts ...grpc.CallOption) (*CreateRatingResponse, error)
	GetCommentsByBeatID(ctx context.Context, in *GetCommentsByBeatIDRequest, opts ...grpc.CallOption) (*GetCommentsByBeatIDResponse, error)
	GetAverageRatingByBeatID(ctx context.Context, in *GetAverageRatingByBeatIDRequest, opts ...grpc.CallOption) (*GetAverageRatingByBeatIDResponse, error)
}

type interactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionServiceClient(cc grpc.ClientConnInterface) InteractionServiceClient {
	return &interactionServiceClient{cc}
}

func (c *interactionServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/interaction.v1.InteractionService/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) CreateRating(ctx context.Context, in *CreateRatingRequest, opts ...grpc.CallOption) (*CreateRatingResponse, error) {
	out := new(CreateRatingResponse)
	err := c.cc.Invoke(ctx, "/interaction.v1.InteractionService/CreateRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetCommentsByBeatID(ctx context.Context, in *GetCommentsByBeatIDRequest, opts ...grpc.CallOption) (*GetCommentsByBeatIDResponse, error) {
	out := new(GetCommentsByBeatIDResponse)
	err := c.cc.Invoke(ctx, "/interaction.v1.InteractionService/GetCommentsByBeatID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetAverageRatingByBeatID(ctx context.Context, in *GetAverageRatingByBeatIDRequest, opts ...grpc.CallOption) (*GetAverageRatingByBeatIDResponse, error) {
	out := new(GetAverageRatingByBeatIDResponse)
	err := c.cc.Invoke(ctx, "/interaction.v1.InteractionService/GetAverageRatingByBeatID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServiceServer is the server API for InteractionService service.
// All implementations must embed UnimplementedInteractionServiceServer
// for forward compatibility
type InteractionServiceServer interface {
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	CreateRating(context.Context, *CreateRatingRequest) (*CreateRatingResponse, error)
	GetCommentsByBeatID(context.Context, *GetCommentsByBeatIDRequest) (*GetCommentsByBeatIDResponse, error)
	GetAverageRatingByBeatID(context.Context, *GetAverageRatingByBeatIDRequest) (*GetAverageRatingByBeatIDResponse, error)
	mustEmbedUnimplementedInteractionServiceServer()
}

// UnimplementedInteractionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInteractionServiceServer struct {
}

func (UnimplementedInteractionServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedInteractionServiceServer) CreateRating(context.Context, *CreateRatingRequest) (*CreateRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRating not implemented")
}
func (UnimplementedInteractionServiceServer) GetCommentsByBeatID(context.Context, *GetCommentsByBeatIDRequest) (*GetCommentsByBeatIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsByBeatID not implemented")
}
func (UnimplementedInteractionServiceServer) GetAverageRatingByBeatID(context.Context, *GetAverageRatingByBeatIDRequest) (*GetAverageRatingByBeatIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAverageRatingByBeatID not implemented")
}
func (UnimplementedInteractionServiceServer) mustEmbedUnimplementedInteractionServiceServer() {}

// UnsafeInteractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServiceServer will
// result in compilation errors.
type UnsafeInteractionServiceServer interface {
	mustEmbedUnimplementedInteractionServiceServer()
}

func RegisterInteractionServiceServer(s grpc.ServiceRegistrar, srv InteractionServiceServer) {
	s.RegisterService(&InteractionService_ServiceDesc, srv)
}

func _InteractionService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interaction.v1.InteractionService/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_CreateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CreateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interaction.v1.InteractionService/CreateRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CreateRating(ctx, req.(*CreateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetCommentsByBeatID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsByBeatIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetCommentsByBeatID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interaction.v1.InteractionService/GetCommentsByBeatID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetCommentsByBeatID(ctx, req.(*GetCommentsByBeatIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetAverageRatingByBeatID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAverageRatingByBeatIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetAverageRatingByBeatID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interaction.v1.InteractionService/GetAverageRatingByBeatID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetAverageRatingByBeatID(ctx, req.(*GetAverageRatingByBeatIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InteractionService_ServiceDesc is the grpc.ServiceDesc for InteractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.v1.InteractionService",
	HandlerType: (*InteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _InteractionService_CreateComment_Handler,
		},
		{
			MethodName: "CreateRating",
			Handler:    _InteractionService_CreateRating_Handler,
		},
		{
			MethodName: "GetCommentsByBeatID",
			Handler:    _InteractionService_GetCommentsByBeatID_Handler,
		},
		{
			MethodName: "GetAverageRatingByBeatID",
			Handler:    _InteractionService_GetAverageRatingByBeatID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/interaction/v1/interaction.proto",
}
