global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth_service:8080']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user_service:8080']

  - job_name: 'beat-service'
    static_configs:
      - targets: ['beat_service:8080']

  - job_name: 'interaction-service'
    static_configs:
      - targets: ['interaction_service:8080']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order_service:8080']

  - job_name: 'wallet-service'
    static_configs:
      - targets: ['wallet_service:8080']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics_service:8080']
