// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.1
// source: api/proto/beat/v1/beat.proto

package beatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Beat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price     float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Tags      []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	AudioUrl  string                 `protobuf:"bytes,5,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	ImageUrl  string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AuthorId  string                 `protobuf:"bytes,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Beat) Reset() {
	*x = Beat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_beat_v1_beat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Beat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beat) ProtoMessage() {}

func (x *Beat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beat_v1_beat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beat.ProtoReflect.Descriptor instead.
func (*Beat) Descriptor() ([]byte, []int) {
	return file_api_proto_beat_v1_beat_proto_rawDescGZIP(), []int{0}
}

func (x *Beat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Beat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Beat) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Beat) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Beat) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *Beat) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Beat) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Beat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Beat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price     float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Tags      []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	AudioData []byte   `protobuf:"bytes,4,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	ImageData []byte   `protobuf:"bytes,5,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	AuthorId  string   `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *CreateBeatRequest) Reset() {
	*x = CreateBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_beat_v1_beat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeatRequest) ProtoMessage() {}

func (x *CreateBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beat_v1_beat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeatRequest.ProtoReflect.Descriptor instead.
func (*CreateBeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beat_v1_beat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBeatRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBeatRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateBeatRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateBeatRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *CreateBeatRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *CreateBeatRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type CreateBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beat *Beat `protobuf:"bytes,1,opt,name=beat,proto3" json:"beat,omitempty"`
}

func (x *CreateBeatResponse) Reset() {
	*x = CreateBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_beat_v1_beat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeatResponse) ProtoMessage() {}

func (x *CreateBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beat_v1_beat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeatResponse.ProtoReflect.Descriptor instead.
func (*CreateBeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beat_v1_beat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBeatResponse) GetBeat() *Beat {
	if x != nil {
		return x.Beat
	}
	return nil
}

type GetBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBeatRequest) Reset() {
	*x = GetBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_beat_v1_beat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeatRequest) ProtoMessage() {}

func (x *GetBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beat_v1_beat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeatRequest.ProtoReflect.Descriptor instead.
func (*GetBeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beat_v1_beat_proto_rawDescGZIP(), []int{3}
}

func (x *GetBeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beat *Beat `protobuf:"bytes,1,opt,name=beat,proto3" json:"beat,omitempty"`
}

func (x *GetBeatResponse) Reset() {
	*x = GetBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_beat_v1_beat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeatResponse) ProtoMessage() {}

func (x *GetBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beat_v1_beat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeatResponse.ProtoReflect.Descriptor instead.
func (*GetBeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beat_v1_beat_proto_rawDescGZIP(), []int{4}
}

func (x *GetBeatResponse) GetBeat() *Beat {
	if x != nil {
		return x.Beat
	}
	return nil
}

type SearchBeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchBeatsRequest) Reset() {
	*x = SearchBeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_beat_v1_beat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBeatsRequest) ProtoMessage() {}

func (x *SearchBeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beat_v1_beat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBeatsRequest.ProtoReflect.Descriptor instead.
func (*SearchBeatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beat_v1_beat_proto_rawDescGZIP(), []int{5}
}

func (x *SearchBeatsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchBeatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beats []*Beat `protobuf:"bytes,1,rep,name=beats,proto3" json:"beats,omitempty"`
}

func (x *SearchBeatsResponse) Reset() {
	*x = SearchBeatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_beat_v1_beat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBeatsResponse) ProtoMessage() {}

func (x *SearchBeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beat_v1_beat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBeatsResponse.ProtoReflect.Descriptor instead.
func (*SearchBeatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beat_v1_beat_proto_rawDescGZIP(), []int{6}
}

func (x *SearchBeatsResponse) GetBeats() []*Beat {
	if x != nil {
		return x.Beats
	}
	return nil
}

var File_api_proto_beat_v1_beat_proto protoreflect.FileDescriptor

var file_api_proto_beat_v1_beat_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x61, 0x74,
	0x2f, 0x76, 0x31, 0x2f, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x02, 0x0a, 0x04, 0x42, 0x65, 0x61,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xae,
	0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22,
	0x37, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65,
	0x61, 0x74, 0x52, 0x04, 0x62, 0x65, 0x61, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x04, 0x62, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x65,
	0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x52, 0x04, 0x62, 0x65, 0x61, 0x74,
	0x22, 0x2a, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x65, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x3a, 0x0a, 0x13,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x62, 0x65, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61,
	0x74, 0x52, 0x05, 0x62, 0x65, 0x61, 0x74, 0x73, 0x32, 0xdc, 0x01, 0x0a, 0x0b, 0x42, 0x65, 0x61,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x12, 0x1a, 0x2e, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x17, 0x2e, 0x62, 0x65, 0x61,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a,
	0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x65, 0x61, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x62,
	0x65, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x65, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x65, 0x61, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x65, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6e, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x61, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x65, 0x61, 0x74,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_beat_v1_beat_proto_rawDescOnce sync.Once
	file_api_proto_beat_v1_beat_proto_rawDescData = file_api_proto_beat_v1_beat_proto_rawDesc
)

func file_api_proto_beat_v1_beat_proto_rawDescGZIP() []byte {
	file_api_proto_beat_v1_beat_proto_rawDescOnce.Do(func() {
		file_api_proto_beat_v1_beat_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_beat_v1_beat_proto_rawDescData)
	})
	return file_api_proto_beat_v1_beat_proto_rawDescData
}

var file_api_proto_beat_v1_beat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_beat_v1_beat_proto_goTypes = []interface{}{
	(*Beat)(nil),                  // 0: beat.v1.Beat
	(*CreateBeatRequest)(nil),     // 1: beat.v1.CreateBeatRequest
	(*CreateBeatResponse)(nil),    // 2: beat.v1.CreateBeatResponse
	(*GetBeatRequest)(nil),        // 3: beat.v1.GetBeatRequest
	(*GetBeatResponse)(nil),       // 4: beat.v1.GetBeatResponse
	(*SearchBeatsRequest)(nil),    // 5: beat.v1.SearchBeatsRequest
	(*SearchBeatsResponse)(nil),   // 6: beat.v1.SearchBeatsResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_api_proto_beat_v1_beat_proto_depIdxs = []int32{
	7, // 0: beat.v1.Beat.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: beat.v1.Beat.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: beat.v1.CreateBeatResponse.beat:type_name -> beat.v1.Beat
	0, // 3: beat.v1.GetBeatResponse.beat:type_name -> beat.v1.Beat
	0, // 4: beat.v1.SearchBeatsResponse.beats:type_name -> beat.v1.Beat
	1, // 5: beat.v1.BeatService.CreateBeat:input_type -> beat.v1.CreateBeatRequest
	3, // 6: beat.v1.BeatService.GetBeat:input_type -> beat.v1.GetBeatRequest
	5, // 7: beat.v1.BeatService.SearchBeats:input_type -> beat.v1.SearchBeatsRequest
	2, // 8: beat.v1.BeatService.CreateBeat:output_type -> beat.v1.CreateBeatResponse
	4, // 9: beat.v1.BeatService.GetBeat:output_type -> beat.v1.GetBeatResponse
	6, // 10: beat.v1.BeatService.SearchBeats:output_type -> beat.v1.SearchBeatsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_beat_v1_beat_proto_init() }
func file_api_proto_beat_v1_beat_proto_init() {
	if File_api_proto_beat_v1_beat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_beat_v1_beat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Beat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_beat_v1_beat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_beat_v1_beat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_beat_v1_beat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_beat_v1_beat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_beat_v1_beat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_beat_v1_beat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBeatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_beat_v1_beat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_beat_v1_beat_proto_goTypes,
		DependencyIndexes: file_api_proto_beat_v1_beat_proto_depIdxs,
		MessageInfos:      file_api_proto_beat_v1_beat_proto_msgTypes,
	}.Build()
	File_api_proto_beat_v1_beat_proto = out.File
	file_api_proto_beat_v1_beat_proto_rawDesc = nil
	file_api_proto_beat_v1_beat_proto_goTypes = nil
	file_api_proto_beat_v1_beat_proto_depIdxs = nil
}
