// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.1
// source: api/proto/beat/v1/beat.proto

package beatv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BeatServiceClient is the client API for BeatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeatServiceClient interface {
	CreateBeat(ctx context.Context, in *CreateBeatRequest, opts ...grpc.CallOption) (*CreateBeatResponse, error)
	GetBeat(ctx context.Context, in *GetBeatRequest, opts ...grpc.CallOption) (*GetBeatResponse, error)
	SearchBeats(ctx context.Context, in *SearchBeatsRequest, opts ...grpc.CallOption) (*SearchBeatsResponse, error)
}

type beatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBeatServiceClient(cc grpc.ClientConnInterface) BeatServiceClient {
	return &beatServiceClient{cc}
}

func (c *beatServiceClient) CreateBeat(ctx context.Context, in *CreateBeatRequest, opts ...grpc.CallOption) (*CreateBeatResponse, error) {
	out := new(CreateBeatResponse)
	err := c.cc.Invoke(ctx, "/beat.v1.BeatService/CreateBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beatServiceClient) GetBeat(ctx context.Context, in *GetBeatRequest, opts ...grpc.CallOption) (*GetBeatResponse, error) {
	out := new(GetBeatResponse)
	err := c.cc.Invoke(ctx, "/beat.v1.BeatService/GetBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beatServiceClient) SearchBeats(ctx context.Context, in *SearchBeatsRequest, opts ...grpc.CallOption) (*SearchBeatsResponse, error) {
	out := new(SearchBeatsResponse)
	err := c.cc.Invoke(ctx, "/beat.v1.BeatService/SearchBeats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeatServiceServer is the server API for BeatService service.
// All implementations must embed UnimplementedBeatServiceServer
// for forward compatibility
type BeatServiceServer interface {
	CreateBeat(context.Context, *CreateBeatRequest) (*CreateBeatResponse, error)
	GetBeat(context.Context, *GetBeatRequest) (*GetBeatResponse, error)
	SearchBeats(context.Context, *SearchBeatsRequest) (*SearchBeatsResponse, error)
	mustEmbedUnimplementedBeatServiceServer()
}

// UnimplementedBeatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBeatServiceServer struct {
}

func (UnimplementedBeatServiceServer) CreateBeat(context.Context, *CreateBeatRequest) (*CreateBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBeat not implemented")
}
func (UnimplementedBeatServiceServer) GetBeat(context.Context, *GetBeatRequest) (*GetBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeat not implemented")
}
func (UnimplementedBeatServiceServer) SearchBeats(context.Context, *SearchBeatsRequest) (*SearchBeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBeats not implemented")
}
func (UnimplementedBeatServiceServer) mustEmbedUnimplementedBeatServiceServer() {}

// UnsafeBeatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeatServiceServer will
// result in compilation errors.
type UnsafeBeatServiceServer interface {
	mustEmbedUnimplementedBeatServiceServer()
}

func RegisterBeatServiceServer(s grpc.ServiceRegistrar, srv BeatServiceServer) {
	s.RegisterService(&BeatService_ServiceDesc, srv)
}

func _BeatService_CreateBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeatServiceServer).CreateBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beat.v1.BeatService/CreateBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeatServiceServer).CreateBeat(ctx, req.(*CreateBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeatService_GetBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeatServiceServer).GetBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beat.v1.BeatService/GetBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeatServiceServer).GetBeat(ctx, req.(*GetBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeatService_SearchBeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeatServiceServer).SearchBeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beat.v1.BeatService/SearchBeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeatServiceServer).SearchBeats(ctx, req.(*SearchBeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeatService_ServiceDesc is the grpc.ServiceDesc for BeatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beat.v1.BeatService",
	HandlerType: (*BeatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBeat",
			Handler:    _BeatService_CreateBeat_Handler,
		},
		{
			MethodName: "GetBeat",
			Handler:    _BeatService_GetBeat_Handler,
		},
		{
			MethodName: "SearchBeats",
			Handler:    _BeatService_SearchBeats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/beat/v1/beat.proto",
}
