// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/events/v1/events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRegisteredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisteredEvent) Reset() {
	*x = UserRegisteredEvent{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisteredEvent) ProtoMessage() {}

func (x *UserRegisteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisteredEvent.ProtoReflect.Descriptor instead.
func (*UserRegisteredEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegisteredEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegisteredEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRegisteredEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegisteredEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserRegisteredEvent) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type UserRatingUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewRating     float64                `protobuf:"fixed64,2,opt,name=new_rating,json=newRating,proto3" json:"new_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRatingUpdatedEvent) Reset() {
	*x = UserRatingUpdatedEvent{}
	mi := &file_api_proto_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRatingUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRatingUpdatedEvent) ProtoMessage() {}

func (x *UserRatingUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRatingUpdatedEvent.ProtoReflect.Descriptor instead.
func (*UserRatingUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserRatingUpdatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRatingUpdatedEvent) GetNewRating() float64 {
	if x != nil {
		return x.NewRating
	}
	return 0
}

var File_api_proto_events_v1_events_proto protoreflect.FileDescriptor

const file_api_proto_events_v1_events_proto_rawDesc = "" +
	"\n" +
	" api/proto/events/v1/events.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x01\n" +
	"\x13UserRegisteredEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"P\n" +
	"\x16UserRatingUpdatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"new_rating\x18\x02 \x01(\x01R\tnewRatingBQZOgithub.com/GO-Trainee/MikitaB-innotaxi-userservice/api/proto/events/v1;eventsv1b\x06proto3"

var (
	file_api_proto_events_v1_events_proto_rawDescOnce sync.Once
	file_api_proto_events_v1_events_proto_rawDescData []byte
)

func file_api_proto_events_v1_events_proto_rawDescGZIP() []byte {
	file_api_proto_events_v1_events_proto_rawDescOnce.Do(func() {
		file_api_proto_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_events_proto_rawDesc), len(file_api_proto_events_v1_events_proto_rawDesc)))
	})
	return file_api_proto_events_v1_events_proto_rawDescData
}

var file_api_proto_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_events_v1_events_proto_goTypes = []any{
	(*UserRegisteredEvent)(nil),    // 0: events.v1.UserRegisteredEvent
	(*UserRatingUpdatedEvent)(nil), // 1: events.v1.UserRatingUpdatedEvent
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_api_proto_events_v1_events_proto_depIdxs = []int32{
	2, // 0: events.v1.UserRegisteredEvent.registered_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_events_v1_events_proto_init() }
func file_api_proto_events_v1_events_proto_init() {
	if File_api_proto_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_events_proto_rawDesc), len(file_api_proto_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_v1_events_proto_goTypes,
		DependencyIndexes: file_api_proto_events_v1_events_proto_depIdxs,
		MessageInfos:      file_api_proto_events_v1_events_proto_msgTypes,
	}.Build()
	File_api_proto_events_v1_events_proto = out.File
	file_api_proto_events_v1_events_proto_goTypes = nil
	file_api_proto_events_v1_events_proto_depIdxs = nil
}
